server:
  port: 3000
  servlet:
    context-path: /api
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Memo?serverTimezone=UTC&useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password:
springdoc:
  paths-to-match:
    - /v1//memos/**
    - /v1//directories/**
    - /v1//users/**
